image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - apk add --no-cache py3-pip
  - pip install docker-compose

build_app:
  stage: build
  script:
    - docker-compose build
  only:
    - main
